### ISSUE TITLE
Write log writer [Helper]

### ISSUE THREAD

**Issue by Tjoosten** [Tjoosten/Website-scouts#70]
The project needs a log write that outputs to a file. Not the database.

## TODO list:
- [x] 01. Basic log system -> 7595efc1c5c5670b89c315eb26de3e5ce2075d52
- [x] 02. Setup config variables in the platform config file. - **Not for this release**
- [x] 03. Inject those variables to the helper. - **Not for this release**
- [x] 04.Write cronjob for mailing the logs of the past month -> to developer. - 21ac639f4873f47efa8ff727890884531a6c6205
- [x] 05. Add cronjob to cronjobs menu ( `CLI`) - 3ac2c5a1dc1722f6d9536fbff4ed1fbcf86d010c
- [x] 06. Add database support for the helper. - 775bcee5c6dd537906eea1f782dade3764d1b07a bfa87e2b8791c22438a4d6f928e04fee9b3eb0fa
   - [x] 6.1. Create instance and load model in the constructor. -> 9d7bc39250ac3b0f0a2d712a7000939fa73b8695
   - [x] 6.2. Model: Insert class. - 775bcee5c6dd537906eea1f782dade3764d1b07a
   - [x] 6.3. Model select class. - bfa87e2b8791c22438a4d6f928e04fee9b3eb0fa
- [x] 07. Setup the model classes into the helper. 775bcee5c6dd537906eea1f782dade3764d1b07a bfa87e2b8791c22438a4d6f928e04fee9b3eb0fa
- [x] 08. Remove old logging code. - b97aede5456ba83698d0191a5ed0f22074f9a127
- [x] 09. Write function that deletes the downloaded logs. e52ad4e35524cb3af9f55023852edf0c8a2b9639
- [x] 10. Rebase code.
- [x] 11. Debug code.
- [x] 12. Merge to master. - **Done Yay!**
